name: example
homepage: https://www.github.com/jonahwilliams/angular-table
author: jonahwilliams <jonahwilliams@google.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  angular: '^4.0.0-alpha'
  angular_components: '0.6.0-alpha+1'
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  angular_table:
    path: '../'

transformers:
- angular:
    entry_points: web/main.dart
- angular/transform/codegen
- angular/transform/reflection_remover:
    $include: test/**_test.dart
- dart_to_js_script_rewriter